const nav = document.querySelector(".nav"), hamb = document.getElementById("hamb");
if (hamb) hamb.onclick = () => nav.classList.toggle("open");
document.querySelectorAll(".nav a").forEach(a => a.addEventListener("click", () => nav.classList.remove("open")));

const obs = new IntersectionObserver(es => es.forEach(e => { if (e.isIntersecting) e.target.classList.add("visible") }), { threshold: .08 });
document.querySelectorAll(".reveal").forEach(x => obs.observe(x));
const progress = document.getElementById("progress");
window.addEventListener("scroll", () => { const h = document.documentElement.scrollHeight - innerHeight; progress.style.width = (h > 0 ? (scrollY / h) * 100 : 0) + "%" }, { passive: true });

document.querySelectorAll(".filters button").forEach(btn => btn.onclick = () => {
    document.querySelectorAll(".filters button").forEach(x => x.classList.remove("active")); btn.classList.add("active");
    const f = btn.dataset.filter; document.querySelectorAll("#scholarGrid .scholar-card").forEach(c => c.style.display = (f === "all" || c.dataset.status === f) ? "flex" : "none");
});

const T = {
    fr: {
        "nav.home": "Accueil", "nav.team": "Équipe & parcours",
        "team.eyebrow": "ÉQUIPE & PARCOURS", "team.title": "Une équipe humaine,<br><em>des parcours réels.</em>", "team.intro": "Découvrez l’équipe ETGI et quelques images de parcours internationaux partagées avec l’accord des personnes concernées.", "team.responsibleRole": "RESPONSABLE ETGI", "team.responsible": "Responsable", "team.responsibleText": "Responsable de l’orientation et du suivi des projets de mobilité internationale.", "team.partnerRole": "PARTENAIRE", "team.partner": "Partenaire", "team.partnerText": "Partenaire présenté dans le cadre des activités d’accompagnement et d’orientation.", "gallery.caption1": "Parcours accompagné — départ international", "gallery.caption2": "Étudiant accompagné", "gallery.caption3": "", "gallery.caption4": "Arrivée internationale", "gallery.caption5": "Parcours étudiant", "gallery.caption6": "Accompagnement académique", "gallery.caption7": "Départ vers l’international", "gallery.caption8": "Arrivée et accompagnement à l’international", "gallery.noteTitle": "Publication avec autorisation", "gallery.note": "Les personnes représentées ont donné leur accord pour la publication de ces images.",
        "trust.eyebrow": "CONFIANCE", "trust.title": "Des démarches claires,<br><em>des informations vérifiables.</em>", "trust.intro": "Nous présentons les voies officielles et distinguons clairement l’accompagnement ETGI des décisions prises par les administrations, ambassades, universités et employeurs.", "trust.card1Title": "Sources officielles", "trust.card1Text": "Les parcours de travail, de formation et d’études renvoient vers les sites officiels lorsque cela est pertinent.", "trust.card2Title": "Accompagnement visa", "trust.card2Text": "ETGI accompagne la préparation d’un projet, avec garantir d'une décision administrative.", "trust.card3Title": "Documents authentiques", "trust.card3Text": "Aucune fausse offre ni faux contrat : un contrat réel doit provenir d’un employeur identifiable.",
        "methods.eyebrow": "NOS MÉTHODES", "methods.title": "Simple. Humain.<br><em>Transparent.</em>", "methods.intro": "Nous avançons avec vous, de la première discussion jusqu’à votre prochaine destination, avec des étapes claires et un accompagnement structuré.", "methods.step1Title": "On échange", "methods.step1Text": "Nous comprenons votre projet et vos objectifs avant de vous orienter vers une démarche adaptée.", "methods.step2Title": "On prépare", "methods.step2Text": "Nous définissons les démarches et les documents nécessaires à votre projet.", "methods.step3Title": "On suit", "methods.step3Text": "Nous vous accompagnons pendant l’avancement de votre dossier et vous indiquons les prochaines étapes.", "methods.step4Title": "Vous partez", "methods.step4Text": "Lorsque les conditions et autorisations sont réunies, vous avancez vers votre prochaine destination.", "methods.noteTitle": "Notre engagement", "methods.noteText": "ETGI vous accompagne avec transparence dans la préparation et le suivi de votre projet. Les admissions, visas, permis et décisions administratives restent de la compétence des autorités concernées.", "nav.services": "Services", "nav.methods": "Nos méthodes", "nav.work": "Travail & Ausbildung", "nav.scholarships": "Bourses", "nav.project": "Votre projet", "nav.contact": "Contact",
        "hero.eyebrow": "TRAVEL · VISA · STUDY · WORK", "hero.title": "Votre monde.<br><em>Votre prochaine</em><br>destination.", "hero.text": "ETGI vous accompagne dans vos projets de voyage, d'études, de travail, d'Ausbildung et de mobilité internationale.", "hero.cta": "Démarrer mon projet →", "hero.more": "Découvrir nos services", "hero.badge": "destinations & voies de mobilité",
        "services.eyebrow": "NOS SERVICES", "services.title": "Un accompagnement pour<br><em>chaque projet.</em>", "services.intro": "Choisissez votre objectif et recevez une orientation structurée selon votre profil et votre destination.",
        "service.visa": "Visa touristique", "service.visaText": "Préparation du projet de voyage et accompagnement documentaire.", "service.study": "Études à l'étranger", "service.studyText": "Orientation, admission, recherche d'opportunités et préparation du dossier.", "service.work": "Travail international", "service.workText": "Orientation vers les voies officielles de recrutement et de permis de travail.", "service.travel": "Voyages & circuits", "service.travelText": "Organisation et orientation pour vos projets touristiques internationaux.", "service.admission": "Admission", "service.admissionText": "Aide à la préparation de candidatures selon le pays et l'établissement.", "service.consult": "Conseil", "service.consultText": "Analyse initiale de votre profil pour identifier les prochaines étapes.", "destinations.label": "DESTINATIONS",
        "work.eyebrow": "TRAVAIL & FORMATION", "work.title": "Des voies réelles pour<br><em>travailler ou se former.</em>", "work.intro": "ETGI présente des dispositifs officiels : contrats de travail, permis, Ausbildung, Express Entry et programmes de mobilité. Aucune fausse offre ni faux contrat.",
        "work.germany.title": "Allemagne — Ausbildung & emploi", "work.germany.text": "Ausbildung en entreprise ou en école, emploi qualifié avec contrat, et accompagnement du projet de visa. Pour une Ausbildung qualifiée, le niveau B1 est généralement demandé selon la situation.", "work.germany.contract": "Contrats : durée déterminée (befristet) ou indéterminée (unbefristet), selon l'employeur.",
        "work.canada.title": "Canada — emploi & Express Entry", "work.canada.text": "Permis de travail lié à un employeur, lorsque les conditions sont remplies, et parcours d'immigration qualifiée via Express Entry.", "work.canada.contract": "Documents possibles : offre d'emploi, contrat et, selon le cas, LMIA ou numéro d'offre.",
        "work.france.title": "France — CDI, CDD & saisonnier", "work.france.text": "Recrutement salarié en contrat à durée indéterminée, déterminée ou saisonnier, avec autorisation de travail lorsque la réglementation l'exige.", "work.france.contract": "Le type de visa dépend notamment de la durée et de la nature du contrat.",
        "work.uk.title": "Royaume-Uni — Skilled Worker", "work.uk.text": "Voie fondée sur un emploi éligible auprès d'un employeur agréé, avec Certificate of Sponsorship et exigences de salaire et d'anglais.", "work.uk.contract": "Le contrat et le sponsorship doivent correspondre au poste proposé.",
        "work.ireland.title": "Irlande — Critical Skills & General Permit", "work.ireland.text": "Permis Critical Skills pour certaines professions hautement qualifiées et General Employment Permit pour de nombreux autres emplois admissibles.", "work.ireland.contract": "Le Critical Skills exige notamment une offre d'emploi d'au moins 2 ans.",
        "work.netherlands.title": "Pays-Bas — Highly Skilled Migrant", "work.netherlands.text": "Pour certains profils qualifiés, l'employeur doit être un sponsor reconnu par l'IND et les conditions de revenus doivent être respectées.", "work.netherlands.contract": "Le contrat de travail doit être conclu avec l'employeur reconnu.",
        "work.belgium.title": "Belgique — Permis unique", "work.belgium.text": "Pour travailler et séjourner plus de 90 jours, l'employeur peut devoir demander un permis unique combinant travail et séjour.", "work.belgium.contract": "La procédure dépend de la région compétente et du profil.",
        "work.switzerland.title": "Suisse — emploi qualifié", "work.switzerland.text": "Pour les ressortissants d'États tiers, l'accès au marché du travail est encadré et vise notamment des profils qualifiés ; l'employeur doit obtenir l'autorisation nécessaire.", "work.switzerland.contract": "Un contrat seul ne suffit pas nécessairement pour obtenir l'autorisation de travail.",
        "work.finland.title": "Finlande — permis de séjour salarié", "work.finland.text": "Une personne venant travailler pour un employeur finlandais doit avoir un emploi confirmé et demander le permis adapté à son activité.", "work.finland.contract": "Le contrat et les conditions d'emploi font partie du dossier.",
        "work.warningTitle": "Important", "work.warning": "ETGI ne fabrique pas de contrats de travail. Un contrat authentique doit provenir d'un employeur réel et être vérifiable. Les visas, permis et autorisations sont décidés par les autorités compétentes.",
        "scholar.eyebrow": "BOURSES", "scholar.title": "Financez votre<br><em>projet d'études.</em>", "scholar.intro": "Une sélection de sources officielles à consulter. Les dates et critères changent : vérifiez toujours la source officielle.", "filter.all": "Toutes", "filter.open": "Opportunités", "filter.watch": "À surveiller", "filter.closed": "Clôturées", "scholar.source": "Voir la source →", "scholar.note": "Les bourses et calendriers évoluent. ETGI ne garantit pas l'obtention d'une bourse ou d'un visa.",
        "project.eyebrow": "VOTRE PROJET", "project.title": "Parlons de<br><em>votre projet.</em>", "project.intro": "Remplissez le formulaire avec précision. Votre demande sera structurée clairement avant l'ouverture de WhatsApp.",
        "form.clean": "DOSSIER STRUCTURÉ", "form.cleanText": "Chaque information est séparée et identifiée pour faciliter son traitement.", "form.secure": "Préparation locale", "form.name": "Nom complet *", "form.email": "Email *", "form.country": "Pays de destination *", "form.type": "Type de projet *", "form.level": "Niveau d'études / profil", "form.phone": "Téléphone / WhatsApp *", "form.description": "Décrivez votre projet *", "form.consent": "J'accepte que ETGI utilise ces informations pour traiter ma demande.", "form.submit": "Générer le dossier & ouvrir WhatsApp →", "form.clear": "Effacer", "form.help": "Un PDF propre sera généré sur votre appareil et un message WhatsApp structuré sera préparé.",
        "testimonials.eyebrow": "TÉMOIGNAGES", "testimonials.title": "Des projets,<br><em>des parcours.</em>", "testimonials.intro": "Espace prévu pour les témoignages réels de vos clients. Remplacez les exemples avant publication.", "testimonials.placeholder1": "Votre témoignage client réel pourra être affiché ici.", "testimonials.placeholder2": "Ajoutez ici une expérience vérifiable et autorisée par le client.", "testimonials.placeholder3": "N'utilisez que des témoignages authentiques et approuvés.", "testimonials.name1": "Client — à remplacer", "testimonials.name2": "Client — à remplacer", "testimonials.name3": "Client — à remplacer",
        "contact.title": "Votre projet mérite<br>un vrai départ.", "contact.wa": "Parler sur WhatsApp →", "footer.note": "Les décisions de visa et d'immigration appartiennent aux autorités compétentes."
    },
    en: {
        "nav.home": "Home", "nav.team": "Team & journeys",
        "team.eyebrow": "TEAM & JOURNEYS", "team.title": "A human team,<br><em>real journeys.</em>", "team.intro": "Meet the ETGI team and discover selected international journey images shared with the consent of the people represented.", "team.responsibleRole": "ETGI RESPONSIBLE", "team.responsible": "Responsible", "team.responsibleText": "Responsible for guidance and follow-up of international mobility projects.", "team.partnerRole": "PARTNER", "team.partner": "Partner", "team.partnerText": "Partner presented as part of our guidance and orientation activities.", "gallery.caption1": "Supported journey — international departure", "gallery.caption2": "Supported student", "gallery.caption3": "", "gallery.caption4": "International arrival", "gallery.caption5": "Student journey", "gallery.caption6": "Academic guidance", "gallery.caption7": "Departure abroad", "gallery.caption8": "International arrival and support", "gallery.noteTitle": "Published with consent", "gallery.note": "The people represented gave their consent for these images to be published.",
        "trust.eyebrow": "TRUST", "trust.title": "Clear processes,<br><em>verifiable information.</em>", "trust.intro": "We present official pathways and clearly distinguish ETGI guidance from decisions made by administrations, embassies, universities and employers.", "trust.card1Title": "Official sources", "trust.card1Text": "Work, training and study pathways link to official websites whenever relevant.", "trust.card2Title": "Visa support", "trust.card2Text": "ETGI supports the preparation of your project, with a guarantee of an administrative decision.", "trust.card3Title": "Authentic documents", "trust.card3Text": "No fake offers or contracts: a genuine contract must come from an identifiable employer.",
        "methods.eyebrow": "OUR METHOD", "methods.title": "A clear method,<br><em>from first contact to departure.</em>", "methods.intro": "We move step by step, with a file adapted to your profile and verifiable information for each pathway.", "methods.step1Title": "Profile review", "methods.step1Text": "We collect your situation, objective, education and experience to understand your project.", "methods.step2Title": "Orientation", "methods.step2Text": "We compare the possible pathways by country: study, work, training, travel or other mobility.", "methods.step3Title": "Application preparation", "methods.step3Text": "We help you organize the information and documents required for the chosen process.", "methods.step4Title": "Procedure follow-up", "methods.step4Text": "We follow the project steps and explain the next actions you need to take.", "methods.step5Title": "Departure preparation", "methods.step5Text": "When the project progresses, we help you prepare the practical aspects of departure and settlement.", "methods.step6Title": "International follow-up", "methods.step6Text": "Depending on the service agreed, we remain available for questions about the next stage of the journey.", "methods.noteTitle": "Our commitment", "methods.noteText": "ETGI supports the process; admissions, visas, permits and immigration decisions remain the responsibility of the relevant authorities, schools and employers.", "nav.services": "Services", "nav.methods": "Our method", "nav.work": "Work & Ausbildung", "nav.scholarships": "Scholarships", "nav.project": "Your project", "nav.contact": "Contact",
        "hero.eyebrow": "TRAVEL · VISA · STUDY · WORK", "hero.title": "Your world.<br><em>Your next</em><br>destination.", "hero.text": "ETGI supports your travel, study, work, Ausbildung and international mobility projects.", "hero.cta": "Start my project →", "hero.more": "Discover our services", "hero.badge": "destinations & mobility pathways",
        "services.eyebrow": "OUR SERVICES", "services.title": "Support for<br><em>every project.</em>", "services.intro": "Choose your objective and receive structured guidance based on your profile and destination.",
        "service.visa": "Tourist visa", "service.visaText": "Travel project preparation and document support.", "service.study": "Study abroad", "service.studyText": "Guidance, admission, opportunity research and application preparation.", "service.work": "International work", "service.workText": "Guidance toward official recruitment and work-permit pathways.", "service.travel": "Travel & tours", "service.travelText": "Planning and guidance for international tourism projects.", "service.admission": "Admission", "service.admissionText": "Application support according to the country and institution.", "service.consult": "Consulting", "service.consultText": "An initial profile review to identify the next steps.", "destinations.label": "DESTINATIONS",
        "work.eyebrow": "WORK & TRAINING", "work.title": "Real pathways to<br><em>work or train abroad.</em>", "work.intro": "ETGI presents official pathways: employment contracts, permits, Ausbildung, Express Entry and mobility programmes. No fake offers or contracts.",
        "work.germany.title": "Germany — Ausbildung & jobs", "work.germany.text": "Company-based or school-based Ausbildung, qualified employment with a contract, and visa guidance. For qualified vocational training, B1 German is generally required depending on the case.", "work.germany.contract": "Contracts: fixed-term (befristet) or open-ended (unbefristet), depending on the employer.",
        "work.canada.title": "Canada — jobs & Express Entry", "work.canada.text": "Employer-specific work permits where requirements are met, plus skilled immigration pathways through Express Entry.", "work.canada.contract": "Possible documents: job offer, employment contract and, depending on the case, LMIA or offer number.",
        "work.france.title": "France — CDI, CDD & seasonal", "work.france.text": "Employment under permanent, fixed-term or seasonal contracts, with work authorisation where required.", "work.france.contract": "The visa type depends in particular on the duration and nature of the contract.",
        "work.uk.title": "United Kingdom — Skilled Worker", "work.uk.text": "A pathway based on an eligible job with an approved employer, a Certificate of Sponsorship, and salary and English-language requirements.", "work.uk.contract": "The contract and sponsorship must match the proposed role.",
        "work.ireland.title": "Ireland — Critical Skills & General Permit", "work.ireland.text": "Critical Skills permits cover certain highly skilled occupations; General Employment Permits cover many other eligible jobs.", "work.ireland.contract": "Critical Skills generally requires a job offer of at least 2 years.",
        "work.netherlands.title": "Netherlands — Highly Skilled Migrant", "work.netherlands.text": "For eligible skilled profiles, the employer must be an IND-recognised sponsor and income requirements must be met.", "work.netherlands.contract": "The employment contract must be with the recognised employer.",
        "work.belgium.title": "Belgium — Single Permit", "work.belgium.text": "For work and residence over 90 days, the employer may need to apply for a single permit combining work and residence authorisation.", "work.belgium.contract": "The procedure depends on the competent region and profile.",
        "work.switzerland.title": "Switzerland — qualified employment", "work.switzerland.text": "For third-country nationals, labour-market access is regulated and focuses on qualified profiles; the employer must obtain the required authorisation.", "work.switzerland.contract": "An employment contract alone does not necessarily grant work authorisation.",
        "work.finland.title": "Finland — employed-person residence permit", "work.finland.text": "A person coming to work for a Finnish employer must have confirmed employment and apply for the appropriate permit.", "work.finland.contract": "The employment contract and terms are part of the application file.",
        "work.warningTitle": "Important", "work.warning": "ETGI does not manufacture employment contracts. A genuine contract must come from a real employer and be verifiable. Visas, permits and authorisations are decided by the competent authorities.",
        "scholar.eyebrow": "SCHOLARSHIPS", "scholar.title": "Fund your<br><em>study project.</em>", "scholar.intro": "A selection of official sources to consult. Dates and criteria change, so always verify the official source.", "filter.all": "All", "filter.open": "Opportunities", "filter.watch": "Watch", "filter.closed": "Closed", "scholar.source": "View source →", "scholar.note": "Scholarships and calendars change. ETGI does not guarantee a scholarship or visa outcome.",
        "project.eyebrow": "YOUR PROJECT", "project.title": "Let's discuss<br><em>your project.</em>", "project.intro": "Complete the form accurately. Your request will be clearly structured before WhatsApp opens.",
        "form.clean": "STRUCTURED FILE", "form.cleanText": "Each piece of information is separated and identified for easier processing.", "form.secure": "Local preparation", "form.name": "Full name *", "form.email": "Email *", "form.country": "Destination country *", "form.type": "Project type *", "form.level": "Education level / profile", "form.phone": "Phone / WhatsApp *", "form.description": "Describe your project *", "form.consent": "I agree that ETGI may use this information to process my request.", "form.submit": "Generate file & open WhatsApp →", "form.clear": "Clear", "form.help": "A clean PDF will be generated on your device and a structured WhatsApp message will be prepared.",
        "testimonials.eyebrow": "TESTIMONIALS", "testimonials.title": "Projects,<br><em>journeys.</em>", "testimonials.intro": "Space reserved for real client testimonials. Replace the examples before publication.", "testimonials.placeholder1": "Your real client testimonial can be displayed here.", "testimonials.placeholder2": "Add a verifiable experience approved by the client here.", "testimonials.placeholder3": "Use authentic and approved testimonials only.", "testimonials.name1": "Client — replace", "testimonials.name2": "Client — replace", "testimonials.name3": "Client — replace",
        "contact.title": "Your project deserves<br>a real start.", "contact.wa": "Chat on WhatsApp →", "footer.note": "Visa and immigration decisions belong to the relevant authorities."
    }
};

let lang = localStorage.getItem("etgiLang") || "fr";
const langBtn = document.getElementById("langBtn");
const scholarTranslations = {
    fr: [
        ["France Excellence / Campus Bourses", "Campus France recense les aides publiques, universitaires et autres financements pour étudiants étrangers.", "À surveiller"],
        ["Master IN — WBI 2026-2027", "Programme de bourses de Wallonie-Bruxelles International pour des masters en Belgique francophone.", "Campagne à vérifier"],
        ["DAAD Scholarship Database", "Le DAAD propose une base de programmes de financement pour étudiants et chercheurs internationaux.", "Opportunités"],
        ["EduCanada — recherche de bourses", "Le portail officiel permet de rechercher des bourses selon la citoyenneté, le profil et le pays ou territoire.", "À vérifier"],
        ["EducationUSA Financial Aid", "EducationUSA recense des possibilités d'aide financière et de bourses pour étudiants internationaux.", "Opportunités"],
        ["Guillaume Dupaix — Université du Luxembourg", "Bourse internationale d'excellence de l'Université du Luxembourg. Les campagnes sont à vérifier selon l'année.", "À surveiller"],
        ["Places financées par l'État / quota", "Le portail officiel présente des possibilités d'études financées par l'État russe, selon les voies d'admission.", "Voie de financement"],
        ["Chinese Government Scholarship", "Les programmes CSC proposent plusieurs catégories de financement. Les dates dépendent du programme et de l'établissement.", "Campagnes variables"],
        ["Swissuniversities — appels ouverts", "Swissuniversities publie des appels de bourses selon les pays et les conditions d'éligibilité.", "À surveiller"],
        ["Bourses universitaires", "Certaines universités finlandaises proposent des exonérations ou aides selon leurs programmes.", "Selon université"],
        ["MFA Scholarship 2026-2027", "Le programme roumain de bourses du ministère des Affaires étrangères est publié par campagne.", "À surveiller"]],
    en: [
        ["France Excellence / Campus Bourses", "Campus France lists public, university and other funding opportunities for international students.", "Watch"],
        ["Master IN — WBI 2026-2027", "Wallonia-Brussels International scholarship programme for master's studies in French-speaking Belgium.", "Check campaign"],
        ["DAAD Scholarship Database", "DAAD provides a database of funding programmes for international students and researchers.", "Opportunities"],
        ["EduCanada — scholarship search", "The official portal helps search scholarships by citizenship, profile and destination.", "Check"],
        ["EducationUSA Financial Aid", "EducationUSA provides information on financial aid and scholarships for international students.", "Opportunities"],
        ["Guillaume Dupaix — University of Luxembourg", "International excellence scholarship at the University of Luxembourg. Check each year's call.", "Watch"],
        ["State-funded places / quota", "The official portal presents state-funded study opportunities through government quota pathways.", "Funding pathway"],
        ["Chinese Government Scholarship", "CSC programmes offer several funding categories; dates vary by programme and institution.", "Variable campaigns"],
        ["Swissuniversities — open calls", "Swissuniversities publishes scholarship calls depending on country and eligibility.", "Watch"],
        ["University scholarships", "Some Finnish universities offer tuition waivers or other support depending on their programmes.", "By university"],
        ["MFA Scholarship 2026-2027", "Romania's Ministry of Foreign Affairs scholarship programme is published by campaign.", "Watch"]]
};

function translateScholarships() {
    const cards = [...document.querySelectorAll("#scholarGrid .scholar-card")];
    cards.forEach((c, i) => { const d = scholarTranslations[lang][i]; if (!d) return; const h = c.querySelector("h3"), p = c.querySelector("p"), b = c.querySelector(".badge"); if (h) h.textContent = d[0]; if (p) p.textContent = d[1]; if (b) b.textContent = d[2] });
}
function applyLang() {
    document.documentElement.lang = lang;
    document.querySelectorAll("[data-i18n]").forEach(el => { const key = el.dataset.i18n; if (T[lang][key]) el.innerHTML = T[lang][key] });
    langBtn.textContent = lang === "fr" ? "EN" : "FR";
    localStorage.setItem("etgiLang", lang);
    translateScholarships();
    const projectTypes = { fr: ["Choisir un projet", "Visa touristique", "Études à l'étranger", "Permis de travail", "Contrat de travail", "Ausbildung (Allemagne)", "Express Entry (Canada)", "Bourse", "Voyage / circuit", "Autre"], en: ["Choose a project", "Tourist visa", "Study abroad", "Work permit", "Employment contract", "Ausbildung (Germany)", "Express Entry (Canada)", "Scholarship", "Travel / tour", "Other"] };
    const countries = { fr: ["Choisir un pays", "Belgique", "Canada", "France", "Allemagne", "États-Unis", "Luxembourg", "Russie", "Chine", "Suisse", "Finlande", "Roumanie", "Royaume-Uni", "Irlande", "Pays-Bas", "Autre"], en: ["Choose a country", "Belgium", "Canada", "France", "Germany", "United States", "Luxembourg", "Russia", "China", "Switzerland", "Finland", "Romania", "United Kingdom", "Ireland", "Netherlands", "Other"] };
    const levels = { fr: ["Non concerné", "Secondaire / Bac", "Licence / Bachelor", "Master", "Doctorat / PhD", "Professionnel"], en: ["Not applicable", "Secondary / High school", "Bachelor", "Master", "PhD", "Professional"] };
    document.querySelectorAll('select[name="project"] option').forEach((o, i) => { if (projectTypes[lang][i]) o.textContent = projectTypes[lang][i] });
    document.querySelectorAll('select[name="country"] option').forEach((o, i) => { if (countries[lang][i]) o.textContent = countries[lang][i] });
    document.querySelectorAll('select[name="level"] option').forEach((o, i) => { if (levels[lang][i]) o.textContent = levels[lang][i] });
}
if (langBtn) langBtn.onclick = () => { lang = lang === "fr" ? "en" : "fr"; applyLang() };
applyLang();

const form = document.getElementById("projectForm"), result = document.getElementById("formResult"), clearBtn = document.getElementById("clearForm");
if (clearBtn) clearBtn.onclick = () => { form.reset(); if (result) result.style.display = "none" };
function getField(name) { return form.querySelector(`[name="${name}"]`)?.value.trim() || "" }
function labelFor(key) { return lang === "fr" ? key.fr : key.en }
function cleanText(s) { return String(s || "").replace(/\r\n/g, "\n").trim() }
function safeFilename(s) { return (s || "client").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9_-]+/gi, "_").replace(/^_+|_+$/g, "") || "client" }

if (form) form.addEventListener("submit", e => {
    e.preventDefault();
    const name = getField("name"), email = getField("email"), phone = getField("phone"), country = getField("country"), project = getField("project"), level = getField("level"), message = cleanText(getField("message"));
    if (!name || !email || !phone || !country || !project || !message) { alert(lang === "fr" ? "Veuillez remplir tous les champs obligatoires." : "Please complete all required fields."); return }
    const consent = form.querySelector('[name="consent"]'); if (!consent.checked) { alert(lang === "fr" ? "Veuillez accepter le traitement de votre demande." : "Please accept the processing of your request."); return }
    const now = new Date(), date = now.toLocaleString(lang === "fr" ? "fr-FR" : "en-GB", { dateStyle: "medium", timeStyle: "short" });
    const { jsPDF } = window.jspdf || {}; if (!jsPDF) { alert("PDF library unavailable."); return }
    const doc = new jsPDF({ unit: "mm", format: "a4" }), margin = 18, max = 174; let y = 22;
    doc.setFillColor(13, 28, 45); doc.rect(0, 0, 210, 38, "F"); doc.setTextColor(215, 173, 97); doc.setFont("helvetica", "bold"); doc.setFontSize(19); doc.text("ETGI", margin, 17); doc.setFontSize(9); doc.text("EXPRESS TRAVEL GROUP INTERNATIONAL", margin, 24); doc.setTextColor(255, 255, 255); doc.setFontSize(9); doc.text(lang === "fr" ? "DEMANDE DE PROJET" : "PROJECT REQUEST", margin, 32);
    y = 50; doc.setTextColor(20, 20, 20); doc.setFontSize(9);
    const rows = [[labelFor({ fr: "Date de la demande", en: "Request date" }), date], [labelFor({ fr: "Nom complet", en: "Full name" }), name], [labelFor({ fr: "Email", en: "Email" }), email], [labelFor({ fr: "Téléphone / WhatsApp", en: "Phone / WhatsApp" }), phone], [labelFor({ fr: "Pays de destination", en: "Destination country" }), country], [labelFor({ fr: "Type de projet", en: "Project type" }), project], [labelFor({ fr: "Niveau / profil", en: "Education / profile" }), level]];
    rows.forEach(([k, v]) => { doc.setFont("helvetica", "bold"); doc.text(k, margin, y); doc.setFont("helvetica", "normal"); doc.text(String(v), margin + 55, y); y += 9 });
    doc.setDrawColor(215, 173, 97); doc.line(margin, y, 192, y); y += 12; doc.setFont("helvetica", "bold"); doc.setFontSize(11); doc.text(labelFor({ fr: "Description du projet", en: "Project description" }), margin, y); y += 8; doc.setFont("helvetica", "normal"); doc.setFontSize(10);
    doc.splitTextToSize(message, max).forEach(line => { if (y > 275) { doc.addPage(); y = 20 } doc.text(line, margin, y); y += 5.5 });
    if (y > 270) { doc.addPage(); y = 20 } doc.setFontSize(8); doc.setTextColor(110, 110, 110); doc.text(lang === "fr" ? "Document généré depuis le site ETGI." : "Document generated from the ETGI website.", margin, y); doc.text(lang === "fr" ? "Les décisions de visa et d'immigration appartiennent aux autorités compétentes." : "Visa and immigration decisions belong to the relevant authorities.", margin, y + 5);
    const filename = `ETGI_${safeFilename(name)}.pdf`; doc.save(filename);
    const wa = [lang === "fr" ? "📋 NOUVELLE DEMANDE — ETGI" : "📋 NEW REQUEST — ETGI", `👤 ${lang === "fr" ? "Nom" : "Name"} : ${name}`, `📧 Email : ${email}`, `📱 ${lang === "fr" ? "Téléphone / WhatsApp" : "Phone / WhatsApp"} : ${phone}`, `🌍 ${lang === "fr" ? "Destination" : "Destination"} : ${country}`, `🎯 ${lang === "fr" ? "Projet" : "Project"} : ${project}`, `📚 ${lang === "fr" ? "Niveau / profil" : "Education / profile"} : ${level}`, "", `📝 ${lang === "fr" ? "DESCRIPTION DU PROJET" : "PROJECT DESCRIPTION"} :`, message].join("\n");
    if (result) { result.textContent = lang === "fr" ? "✓ Dossier PDF généré. WhatsApp va s'ouvrir avec votre demande structurée." : "✓ PDF generated. WhatsApp will open with your structured request."; result.style.display = "block" }
    setTimeout(() => window.open("https://wa.me/4915216395810?text=" + encodeURIComponent(wa), "_blank"), 250);
});
